### ISSUE TITLE
New message structure for client

### ISSUE THREAD

**Issue by code-to-gold** [paust-team/shapleq#120]
To integrate the ShapleQ with HBase or other KVStore, a record should contain key and value.
I suggest the new message structure as below.

* ProducerRecord
```go
type ProducerRecord struct {
    Key []byte
    Value []byte
    Time time.Time
}
```

* ConsumerRecord
```go
type ConsumerRecord struct {
    Topic string
    Partition uint
    Key []byte
    Value []byte
    Offset uint64
    Time time.Time
}
```

**Comment by code-to-gold** [comment]
The key and value have to be serialized and store as the value of rocksdb.
I suggest serialization as below.
`[key-length][key-data][value-length][value-data]`
Both key-length and value-length are 2byte so that it can represent 0 to 65536 byte length.

**Comment by code-to-gold** [comment]
For now, the producer's `Publish()` method returns `Partition` and `error` but the `Partition` isn't worthy to utilize. 
So I'm gonna log the written partition but will not return it.

**Comment by code-to-gold** [comment]
In addition, `Publish()` method should be changed to receive records as a variadic parameter. It is useful when publishing bounded data and batch publishing.

**Comment by elon0823** [comment]
> The key and value have to be serialized and store as the value of rocksdb.
> I suggest serialization as below.
> `[key-length][key-data][value-length][value-data]`
> Both key-length and value-length are 2byte so that it can represent 0 to 65536 byte length.

How about designing serialization structure with fixed length header and followed by variadic length value?
Then the header will consist of 4bytes of [key-length][value-length].

**Comment by elon0823** [comment]
Why is Partition `uint` type? Is it just represents partition id?

**Comment by code-to-gold** [comment]
> > The key and value have to be serialized and store as the value of rocksdb.
> > I suggest serialization as below.
> > `[key-length][key-data][value-length][value-data]`
> > Both key-length and value-length are 2byte so that it can represent 0 to 65536 byte length.
> 
> How about designing serialization structure with fixed length header and followed by variadic length value?
> Then the header will consist of 4bytes of [key-length][value-length].

If what I designed is a protocol, and has lots of information in it, It's nice to have the header in it.
But it's the data body. Length - data structure is useful because it can be encoded/decoded recursively and also it can represent the hierarchical structure.

**Comment by code-to-gold** [comment]
> Why is Partition `uint` type? Is it just represents partition id?

Yes its partition ID,.

**Comment by elon0823** [comment]
staled issue
