### ISSUE TITLE
Refactor busy-waiting select-case loops for resource efficiency

### ISSUE THREAD

**Issue by elon0823** [paust-team/shapleq#162]
### The high CPU resource issues
We currently used a `default` statement at some select-case loops as busy-waiting semantic in the ShapleQ. Those caused exhaustion of EC2's vCPU credits from high CPU usage(over 99%). Also, there is a possibility of the CPU starvation if other processes(monitoring, logging, etc) are running altogether. We planned to use `time.Sleep()` between each iteration in every busy-waiting loops that can lead to CPU exhaustion.

But I found some articles( [1](https://stackoverflow.com/questions/48689759/sleep-in-goroutine-with-busy-loop?rq=1), [2](https://betterprogramming.pub/working-on-high-performance-golang-client-library-remove-the-bad-busy-loops-with-the-sync-cond-e262b3fcb458) ) and they said:

> Using calls to time.Sleep is never the right option for coordination of concurrent processes, and it is better to rely on synchronization primitives and the runtime to coordinate the concurrency whenever possible

### Remove busy-waiting semantics
The busy-waiting technique is a quite general solution for dealing with the event I/O with an event queue. However in golang, it is always better to use the `channel` or some other synchronization techniques provided in the `sync` standard package.

Since we are already handling concurrency through the `channel`, we only need to delete the `default` statement from all select-case loops.

**Comment by 1dennispark** [comment]
Thank you for your good sharing. This knowledge is important for using goroutines.
