### ISSUE TITLE
Design zookeeper node to store topic(partition) state and consumer offset in it

### ISSUE THREAD

**Issue by code-to-gold** [paust-team/shapleq#95]
This issue suggests the enhanced design of zookeeper node for the following reasons. 
* To move the storage of topic(partition) state from shapleq broker to zookeeper
* Store consumer offset in zookeeper so that consumers can manage the offset themselves.
* To support partition in the future (partition number gonna be fixed as one currently)

## Broker info
Broker connection information
### path 
`/shapleq/brokers/{broker_id}`
### data
```
{
    “version”: 1,
    “host”: “168.32.3.59”,
    “port”: 1234
}
```

## Topic metadata
topic name and rarely changed data.
### path
`/shapleq/topics/{topic}`
### data
```
{
    “version”: 1,
    “meta”: “New topic”,
    “partitions”: {“0”: [1, 3, 5], “1”: [2, 4, 6]}
}
```

### path
`/shapleq/topics/{topic}/partitions/{partition_id}`
### data
```
{
    “version”: 1,
    “num_pubs”: 3,
    “num_subs”: 3,
    “last_offset”: 10
}
```

### path
`/shapleq/consumers/{id}/offset/{topic}/{partition_id}`

### data
`uint64(offset)`

## Lock related nodes
`/shapleq/locknode/topics`: lock for add and deletion of topic
`/shapleq/locknode/topic/{topic}` : lock for update of topic
`/shapleq/locknode/partitions/{topic}-{partition_id}`: read/write lock of partition state 
`/shapleq/locknode/brokers`: write lock of broker

Data related to the replication factor gonna be added further.

**Comment by elon0823** [comment]
partition is replaced with fragment. #141
